/**
 * @module modules/parser/skills-extractor
 * @description Extracts and classifies skills from resume text using a 200+ skill taxonomy.
 * Supports comma-separated, categorized, bullet, and pipe-separated formats.
 */

import type { SkillSet } from "./types";

/** Skill taxonomy mapping skill names to SkillSet categories */
const SKILL_TAXONOMY: Record<string, keyof SkillSet> = {
  // Languages
  python: "languages",
  java: "languages",
  javascript: "languages",
  typescript: "languages",
  go: "languages",
  golang: "languages",
  rust: "languages",
  "c++": "languages",
  "c#": "languages",
  ruby: "languages",
  php: "languages",
  swift: "languages",
  kotlin: "languages",
  scala: "languages",
  r: "languages",
  matlab: "languages",
  perl: "languages",
  lua: "languages",
  haskell: "languages",
  elixir: "languages",
  erlang: "languages",
  clojure: "languages",
  dart: "languages",
  "objective-c": "languages",
  groovy: "languages",
  julia: "languages",
  fortran: "languages",
  cobol: "languages",
  assembly: "languages",
  vhdl: "languages",
  verilog: "languages",
  sql: "languages",
  html: "languages",
  css: "languages",
  sass: "languages",
  less: "languages",
  bash: "languages",
  shell: "languages",
  powershell: "languages",
  c: "languages",

  // Frameworks
  react: "technical",
  "react.js": "technical",
  "reactjs": "technical",
  angular: "technical",
  "angular.js": "technical",
  vue: "technical",
  "vue.js": "technical",
  "vuejs": "technical",
  svelte: "technical",
  "next.js": "technical",
  nextjs: "technical",
  "nuxt.js": "technical",
  nuxtjs: "technical",
  gatsby: "technical",
  remix: "technical",
  django: "technical",
  flask: "technical",
  fastapi: "technical",
  spring: "technical",
  "spring boot": "technical",
  express: "technical",
  "express.js": "technical",
  nestjs: "technical",
  "nest.js": "technical",
  koa: "technical",
  fastify: "technical",
  "ruby on rails": "technical",
  rails: "technical",
  laravel: "technical",
  symfony: "technical",
  ".net": "technical",
  "asp.net": "technical",
  blazor: "technical",
  gin: "technical",
  echo: "technical",
  fiber: "technical",
  actix: "technical",
  rocket: "technical",
  phoenix: "technical",
  flutter: "technical",
  "react native": "technical",
  ionic: "technical",
  xamarin: "technical",
  electron: "technical",
  tauri: "technical",
  "tailwind css": "technical",
  tailwind: "technical",
  bootstrap: "technical",
  "material ui": "technical",
  mui: "technical",
  "chakra ui": "technical",
  "ant design": "technical",
  jquery: "technical",
  backbone: "technical",
  ember: "technical",
  "d3.js": "technical",
  "three.js": "technical",
  tensorflow: "technical",
  pytorch: "technical",
  keras: "technical",
  scikit: "technical",
  "scikit-learn": "technical",
  pandas: "technical",
  numpy: "technical",
  scipy: "technical",
  matplotlib: "technical",
  seaborn: "technical",
  opencv: "technical",
  spark: "technical",
  hadoop: "technical",
  kafka: "technical",
  "apache kafka": "technical",
  airflow: "technical",
  celery: "technical",
  "redux": "technical",
  "mobx": "technical",
  "zustand": "technical",
  graphql: "technical",
  "rest api": "technical",
  "restful api": "technical",
  "rest apis": "technical",
  grpc: "technical",
  websocket: "technical",
  webrtc: "technical",
  oauth: "technical",
  jwt: "technical",
  saml: "technical",
  openid: "technical",

  // Tools
  docker: "tools",
  kubernetes: "tools",
  k8s: "tools",
  git: "tools",
  github: "tools",
  gitlab: "tools",
  bitbucket: "tools",
  jenkins: "tools",
  "github actions": "tools",
  "gitlab ci": "tools",
  "circle ci": "tools",
  circleci: "tools",
  "travis ci": "tools",
  terraform: "tools",
  ansible: "tools",
  puppet: "tools",
  chef: "tools",
  vagrant: "tools",
  packer: "tools",
  helm: "tools",
  istio: "tools",
  prometheus: "tools",
  grafana: "tools",
  datadog: "tools",
  "new relic": "tools",
  splunk: "tools",
  elk: "tools",
  elasticsearch: "tools",
  logstash: "tools",
  kibana: "tools",
  nginx: "tools",
  apache: "tools",
  caddy: "tools",
  haproxy: "tools",
  aws: "tools",
  "amazon web services": "tools",
  azure: "tools",
  "microsoft azure": "tools",
  gcp: "tools",
  "google cloud": "tools",
  "google cloud platform": "tools",
  heroku: "tools",
  vercel: "tools",
  netlify: "tools",
  digitalocean: "tools",
  cloudflare: "tools",
  firebase: "tools",
  supabase: "tools",
  mongodb: "tools",
  postgresql: "tools",
  postgres: "tools",
  mysql: "tools",
  redis: "tools",
  memcached: "tools",
  dynamodb: "tools",
  cassandra: "tools",
  couchdb: "tools",
  neo4j: "tools",
  influxdb: "tools",
  sqlite: "tools",
  mariadb: "tools",
  "oracle db": "tools",
  "sql server": "tools",
  snowflake: "tools",
  bigquery: "tools",
  redshift: "tools",
  databricks: "tools",
  jira: "tools",
  confluence: "tools",
  trello: "tools",
  asana: "tools",
  notion: "tools",
  slack: "tools",
  figma: "tools",
  sketch: "tools",
  "adobe xd": "tools",
  invision: "tools",
  "vs code": "tools",
  "visual studio code": "tools",
  "visual studio": "tools",
  intellij: "tools",
  "intellij idea": "tools",
  webstorm: "tools",
  pycharm: "tools",
  eclipse: "tools",
  vim: "tools",
  neovim: "tools",
  emacs: "tools",
  postman: "tools",
  insomnia: "tools",
  swagger: "tools",
  storybook: "tools",
  webpack: "tools",
  vite: "tools",
  esbuild: "tools",
  rollup: "tools",
  parcel: "tools",
  babel: "tools",
  npm: "tools",
  yarn: "tools",
  pnpm: "tools",
  pip: "tools",
  maven: "tools",
  gradle: "tools",
  cargo: "tools",
  sbt: "tools",
  make: "tools",
  cmake: "tools",
  "rabbitmq": "tools",
  "amazon s3": "tools",
  s3: "tools",
  lambda: "tools",
  "aws lambda": "tools",
  ec2: "tools",
  ecs: "tools",
  eks: "tools",
  fargate: "tools",
  cloudformation: "tools",
  pulumi: "tools",
  linux: "tools",
  unix: "tools",
  windows: "tools",
  macos: "tools",

  // Technical concepts
  "machine learning": "technical",
  "deep learning": "technical",
  "natural language processing": "technical",
  nlp: "technical",
  "computer vision": "technical",
  "artificial intelligence": "technical",
  ai: "technical",
  "data science": "technical",
  "data engineering": "technical",
  "data analysis": "technical",
  "data visualization": "technical",
  "big data": "technical",
  etl: "technical",
  "data structures": "technical",
  algorithms: "technical",
  "system design": "technical",
  microservices: "technical",
  monolith: "technical",
  "event-driven": "technical",
  "domain-driven design": "technical",
  ddd: "technical",
  tdd: "technical",
  "test-driven development": "technical",
  bdd: "technical",
  "ci/cd": "technical",
  devops: "technical",
  devsecops: "technical",
  sre: "technical",
  "site reliability": "technical",
  "cloud computing": "technical",
  serverless: "technical",
  iaas: "technical",
  paas: "technical",
  saas: "technical",
  "distributed systems": "technical",
  "high availability": "technical",
  scalability: "technical",
  caching: "technical",
  "load balancing": "technical",
  "api design": "technical",
  "database design": "technical",
  "object-oriented programming": "technical",
  oop: "technical",
  "functional programming": "technical",
  "reactive programming": "technical",
  concurrency: "technical",
  multithreading: "technical",
  networking: "technical",
  security: "technical",
  cryptography: "technical",
  encryption: "technical",
  "web development": "technical",
  "mobile development": "technical",
  "full-stack": "technical",
  "front-end": "technical",
  "back-end": "technical",
  frontend: "technical",
  backend: "technical",
  fullstack: "technical",
  "unit testing": "technical",
  "integration testing": "technical",
  "e2e testing": "technical",
  "end-to-end testing": "technical",
  "performance testing": "technical",
  "load testing": "technical",
  "a/b testing": "technical",
  accessibility: "technical",
  seo: "technical",
  pwa: "technical",
  responsive: "technical",
  "responsive design": "technical",
  "blockchain": "technical",
  "web3": "technical",
  "smart contracts": "technical",
  "cloud architecture": "technical",
  "software architecture": "technical",
  "design patterns": "technical",
  "clean code": "technical",
  refactoring: "technical",
  "code review": "technical",
  debugging: "technical",
  profiling: "technical",
  optimization: "technical",
  "version control": "technical",

  // Soft skills
  leadership: "soft",
  communication: "soft",
  teamwork: "soft",
  collaboration: "soft",
  "problem solving": "soft",
  "problem-solving": "soft",
  "critical thinking": "soft",
  creativity: "soft",
  adaptability: "soft",
  "time management": "soft",
  "project management": "soft",
  mentoring: "soft",
  coaching: "soft",
  presentation: "soft",
  "public speaking": "soft",
  negotiation: "soft",
  "conflict resolution": "soft",
  empathy: "soft",
  initiative: "soft",
  "self-motivated": "soft",
  "detail-oriented": "soft",
  "analytical thinking": "soft",
  agile: "soft",
  scrum: "soft",
  kanban: "soft",
  waterfall: "soft",
  "cross-functional": "soft",
  stakeholder: "soft",
  "stakeholder management": "soft",
  "customer focus": "soft",
  "strategic thinking": "soft",
  "decision making": "soft",
  "decision-making": "soft",
  "risk management": "soft",
  planning: "soft",
  organization: "soft",
  prioritization: "soft",
  multitasking: "soft",
  flexibility: "soft",
  resilience: "soft",
  accountability: "soft",
  integrity: "soft",
  "work ethic": "soft",
  enthusiasm: "soft",
  motivation: "soft",
  "emotional intelligence": "soft",
};

/** Category header pattern for categorized skill formats */
const CATEGORY_HEADER_RE = /^([A-Za-z\s/&]+)[:\-–—]\s*(.+)$/;

/**
 * Extract and classify skills from a section's text.
 *
 * @param sectionText - The raw text of the skills section
 * @returns Classified SkillSet
 */
export function extractSkills(sectionText: string): SkillSet {
  const result: SkillSet = {
    technical: [],
    soft: [],
    tools: [],
    languages: [],
  };

  if (!sectionText || sectionText.trim().length === 0) {
    return result;
  }

  const lines = sectionText.split("\n");
  const allSkills: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;

    // Remove bullet prefixes
    const cleaned = trimmed.replace(/^\s*[-•*>]\s+/, "");

    // Check for categorized format: "Languages: Python, Java, JavaScript"
    const catMatch = cleaned.match(CATEGORY_HEADER_RE);
    if (catMatch) {
      const skills = splitSkills(catMatch[2]);
      allSkills.push(...skills);
      continue;
    }

    // Split by common delimiters
    const skills = splitSkills(cleaned);
    allSkills.push(...skills);
  }

  // Classify each skill
  const seen = new Set<string>();
  for (const skill of allSkills) {
    const normalized = skill.toLowerCase().trim();
    if (normalized.length === 0) continue;
    if (seen.has(normalized)) continue;
    seen.add(normalized);

    const category = SKILL_TAXONOMY[normalized];
    if (category) {
      const arr = result[category];
      if (Array.isArray(arr)) {
        arr.push(skill.trim());
      }
    } else {
      // Unknown skills go to technical as "other"
      result.technical.push(skill.trim());
    }
  }

  return result;
}

/**
 * Split a string of skills by common delimiters.
 */
function splitSkills(text: string): string[] {
  // Split by comma, pipe, or semicolon
  return text
    .split(/[,|;]/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && s.length < 60);
}
