/**
 * @module modules/ats/keyword-database
 * @description Comprehensive tech keyword database for ATS keyword matching.
 * Contains 500+ industry terms mapped to categories, plus curated action verb
 * and weak verb lists for bullet point analysis.
 */

// ── Tech Keyword Database (lowercase → category) ──────────

const entries: [string, string][] = [
    // ─── Programming Languages (65+) ────────────────────────
    ["python", "Programming Languages"],
    ["java", "Programming Languages"],
    ["javascript", "Programming Languages"],
    ["typescript", "Programming Languages"],
    ["c++", "Programming Languages"],
    ["c#", "Programming Languages"],
    ["c", "Programming Languages"],
    ["go", "Programming Languages"],
    ["golang", "Programming Languages"],
    ["rust", "Programming Languages"],
    ["kotlin", "Programming Languages"],
    ["swift", "Programming Languages"],
    ["ruby", "Programming Languages"],
    ["php", "Programming Languages"],
    ["scala", "Programming Languages"],
    ["r", "Programming Languages"],
    ["matlab", "Programming Languages"],
    ["perl", "Programming Languages"],
    ["haskell", "Programming Languages"],
    ["elixir", "Programming Languages"],
    ["erlang", "Programming Languages"],
    ["clojure", "Programming Languages"],
    ["lua", "Programming Languages"],
    ["dart", "Programming Languages"],
    ["objective-c", "Programming Languages"],
    ["assembly", "Programming Languages"],
    ["cobol", "Programming Languages"],
    ["fortran", "Programming Languages"],
    ["groovy", "Programming Languages"],
    ["julia", "Programming Languages"],
    ["f#", "Programming Languages"],
    ["visual basic", "Programming Languages"],
    ["vb.net", "Programming Languages"],
    ["powershell", "Programming Languages"],
    ["bash", "Programming Languages"],
    ["shell scripting", "Programming Languages"],
    ["sql", "Programming Languages"],
    ["plsql", "Programming Languages"],
    ["t-sql", "Programming Languages"],
    ["solidity", "Programming Languages"],
    ["zig", "Programming Languages"],
    ["nim", "Programming Languages"],
    ["crystal", "Programming Languages"],
    ["ocaml", "Programming Languages"],
    ["scheme", "Programming Languages"],
    ["prolog", "Programming Languages"],
    ["lisp", "Programming Languages"],
    ["common lisp", "Programming Languages"],
    ["racket", "Programming Languages"],
    ["ada", "Programming Languages"],
    ["d", "Programming Languages"],
    ["apex", "Programming Languages"],
    ["abap", "Programming Languages"],
    ["vhdl", "Programming Languages"],
    ["verilog", "Programming Languages"],
    ["sas", "Programming Languages"],
    ["stata", "Programming Languages"],
    ["labview", "Programming Languages"],
    ["scratch", "Programming Languages"],
    ["coffeescript", "Programming Languages"],
    ["actionscript", "Programming Languages"],
    ["hack", "Programming Languages"],
    ["wasm", "Programming Languages"],
    ["webassembly", "Programming Languages"],
    ["html", "Programming Languages"],
    ["css", "Programming Languages"],

    // ─── Frameworks & Libraries (90+) ───────────────────────
    ["react", "Frameworks"],
    ["react.js", "Frameworks"],
    ["reactjs", "Frameworks"],
    ["angular", "Frameworks"],
    ["vue", "Frameworks"],
    ["vue.js", "Frameworks"],
    ["vuejs", "Frameworks"],
    ["next.js", "Frameworks"],
    ["nextjs", "Frameworks"],
    ["nuxt", "Frameworks"],
    ["nuxt.js", "Frameworks"],
    ["svelte", "Frameworks"],
    ["sveltekit", "Frameworks"],
    ["django", "Frameworks"],
    ["flask", "Frameworks"],
    ["fastapi", "Frameworks"],
    ["spring", "Frameworks"],
    ["spring boot", "Frameworks"],
    ["express", "Frameworks"],
    ["express.js", "Frameworks"],
    ["nest.js", "Frameworks"],
    ["nestjs", "Frameworks"],
    ["rails", "Frameworks"],
    ["ruby on rails", "Frameworks"],
    ["laravel", "Frameworks"],
    [".net", "Frameworks"],
    ["asp.net", "Frameworks"],
    ["asp.net core", "Frameworks"],
    ["blazor", "Frameworks"],
    ["sinatra", "Frameworks"],
    ["gin", "Frameworks"],
    ["echo", "Frameworks"],
    ["fiber", "Frameworks"],
    ["actix", "Frameworks"],
    ["rocket", "Frameworks"],
    ["phoenix", "Frameworks"],
    ["ktor", "Frameworks"],
    ["gatsby", "Frameworks"],
    ["remix", "Frameworks"],
    ["astro", "Frameworks"],
    ["solid.js", "Frameworks"],
    ["solidjs", "Frameworks"],
    ["qwik", "Frameworks"],
    ["ember", "Frameworks"],
    ["ember.js", "Frameworks"],
    ["backbone", "Frameworks"],
    ["backbone.js", "Frameworks"],
    ["jquery", "Frameworks"],
    ["bootstrap", "Frameworks"],
    ["tailwindcss", "Frameworks"],
    ["tailwind css", "Frameworks"],
    ["tailwind", "Frameworks"],
    ["material ui", "Frameworks"],
    ["mui", "Frameworks"],
    ["ant design", "Frameworks"],
    ["chakra ui", "Frameworks"],
    ["styled-components", "Frameworks"],
    ["emotion", "Frameworks"],
    ["redux", "Frameworks"],
    ["mobx", "Frameworks"],
    ["zustand", "Frameworks"],
    ["recoil", "Frameworks"],
    ["jotai", "Frameworks"],
    ["rxjs", "Frameworks"],
    ["node.js", "Frameworks"],
    ["nodejs", "Frameworks"],
    ["deno", "Frameworks"],
    ["bun", "Frameworks"],
    ["electron", "Frameworks"],
    ["react native", "Frameworks"],
    ["flutter", "Frameworks"],
    ["ionic", "Frameworks"],
    ["xamarin", "Frameworks"],
    ["unity", "Frameworks"],
    ["unreal engine", "Frameworks"],
    ["three.js", "Frameworks"],
    ["d3.js", "Frameworks"],
    ["d3", "Frameworks"],
    ["chart.js", "Frameworks"],
    ["storybook", "Frameworks"],
    ["cypress", "Frameworks"],
    ["playwright", "Frameworks"],
    ["puppeteer", "Frameworks"],
    ["selenium", "Frameworks"],
    ["jest", "Frameworks"],
    ["mocha", "Frameworks"],
    ["vitest", "Frameworks"],
    ["pytest", "Frameworks"],
    ["junit", "Frameworks"],
    ["testng", "Frameworks"],
    ["spring security", "Frameworks"],
    ["hibernate", "Frameworks"],

    // ─── Databases (35+) ────────────────────────────────────
    ["postgresql", "Databases"],
    ["postgres", "Databases"],
    ["mysql", "Databases"],
    ["mongodb", "Databases"],
    ["redis", "Databases"],
    ["elasticsearch", "Databases"],
    ["dynamodb", "Databases"],
    ["cassandra", "Databases"],
    ["sqlite", "Databases"],
    ["oracle", "Databases"],
    ["oracle db", "Databases"],
    ["sql server", "Databases"],
    ["mssql", "Databases"],
    ["neo4j", "Databases"],
    ["couchdb", "Databases"],
    ["couchbase", "Databases"],
    ["firebase", "Databases"],
    ["firestore", "Databases"],
    ["supabase", "Databases"],
    ["mariadb", "Databases"],
    ["cockroachdb", "Databases"],
    ["timescaledb", "Databases"],
    ["influxdb", "Databases"],
    ["clickhouse", "Databases"],
    ["memcached", "Databases"],
    ["hbase", "Databases"],
    ["arangodb", "Databases"],
    ["rethinkdb", "Databases"],
    ["amazon rds", "Databases"],
    ["aurora", "Databases"],
    ["amazon aurora", "Databases"],
    ["planetscale", "Databases"],
    ["prisma", "Databases"],
    ["drizzle", "Databases"],
    ["typeorm", "Databases"],
    ["sequelize", "Databases"],
    ["mongoose", "Databases"],
    ["knex", "Databases"],

    // ─── Cloud & Infrastructure (45+) ───────────────────────
    ["aws", "Cloud"],
    ["amazon web services", "Cloud"],
    ["gcp", "Cloud"],
    ["google cloud", "Cloud"],
    ["google cloud platform", "Cloud"],
    ["azure", "Cloud"],
    ["microsoft azure", "Cloud"],
    ["ec2", "Cloud"],
    ["s3", "Cloud"],
    ["lambda", "Cloud"],
    ["aws lambda", "Cloud"],
    ["rds", "Cloud"],
    ["cloudfront", "Cloud"],
    ["ecs", "Cloud"],
    ["eks", "Cloud"],
    ["fargate", "Cloud"],
    ["sqs", "Cloud"],
    ["sns", "Cloud"],
    ["cloudformation", "Cloud"],
    ["cdk", "Cloud"],
    ["aws cdk", "Cloud"],
    ["api gateway", "Cloud"],
    ["route 53", "Cloud"],
    ["cloudwatch", "Cloud"],
    ["iam", "Cloud"],
    ["vpc", "Cloud"],
    ["elastic beanstalk", "Cloud"],
    ["step functions", "Cloud"],
    ["kinesis", "Cloud"],
    ["redshift", "Cloud"],
    ["athena", "Cloud"],
    ["glue", "Cloud"],
    ["sagemaker", "Cloud"],
    ["cloud run", "Cloud"],
    ["cloud functions", "Cloud"],
    ["bigquery", "Cloud"],
    ["cloud storage", "Cloud"],
    ["gke", "Cloud"],
    ["app engine", "Cloud"],
    ["azure functions", "Cloud"],
    ["azure devops", "Cloud"],
    ["cosmos db", "Cloud"],
    ["blob storage", "Cloud"],
    ["aks", "Cloud"],
    ["digital ocean", "Cloud"],
    ["digitalocean", "Cloud"],
    ["heroku", "Cloud"],
    ["vercel", "Cloud"],
    ["netlify", "Cloud"],
    ["railway", "Cloud"],
    ["render", "Cloud"],
    ["fly.io", "Cloud"],
    ["cloudflare", "Cloud"],
    ["cloudflare workers", "Cloud"],

    // ─── DevOps & Infrastructure Tools (45+) ────────────────
    ["docker", "DevOps"],
    ["kubernetes", "DevOps"],
    ["k8s", "DevOps"],
    ["terraform", "DevOps"],
    ["ansible", "DevOps"],
    ["puppet", "DevOps"],
    ["chef", "DevOps"],
    ["jenkins", "DevOps"],
    ["github actions", "DevOps"],
    ["gitlab ci", "DevOps"],
    ["gitlab ci/cd", "DevOps"],
    ["circleci", "DevOps"],
    ["travis ci", "DevOps"],
    ["bitbucket pipelines", "DevOps"],
    ["argo cd", "DevOps"],
    ["argocd", "DevOps"],
    ["prometheus", "DevOps"],
    ["grafana", "DevOps"],
    ["datadog", "DevOps"],
    ["new relic", "DevOps"],
    ["splunk", "DevOps"],
    ["elk stack", "DevOps"],
    ["logstash", "DevOps"],
    ["kibana", "DevOps"],
    ["fluentd", "DevOps"],
    ["nginx", "DevOps"],
    ["apache", "DevOps"],
    ["caddy", "DevOps"],
    ["haproxy", "DevOps"],
    ["consul", "DevOps"],
    ["vault", "DevOps"],
    ["hashicorp vault", "DevOps"],
    ["helm", "DevOps"],
    ["istio", "DevOps"],
    ["envoy", "DevOps"],
    ["linkerd", "DevOps"],
    ["packer", "DevOps"],
    ["vagrant", "DevOps"],
    ["podman", "DevOps"],
    ["containerd", "DevOps"],
    ["openshift", "DevOps"],
    ["rancher", "DevOps"],
    ["sonarqube", "DevOps"],
    ["nexus", "DevOps"],
    ["artifactory", "DevOps"],
    ["sentry", "DevOps"],
    ["pagerduty", "DevOps"],
    ["opsgenie", "DevOps"],

    // ─── AI / ML / Data Science (35+) ───────────────────────
    ["tensorflow", "AI/ML"],
    ["pytorch", "AI/ML"],
    ["scikit-learn", "AI/ML"],
    ["sklearn", "AI/ML"],
    ["pandas", "AI/ML"],
    ["numpy", "AI/ML"],
    ["keras", "AI/ML"],
    ["hugging face", "AI/ML"],
    ["huggingface", "AI/ML"],
    ["transformers", "AI/ML"],
    ["langchain", "AI/ML"],
    ["openai", "AI/ML"],
    ["llm", "AI/ML"],
    ["large language model", "AI/ML"],
    ["nlp", "AI/ML"],
    ["natural language processing", "AI/ML"],
    ["computer vision", "AI/ML"],
    ["deep learning", "AI/ML"],
    ["machine learning", "AI/ML"],
    ["reinforcement learning", "AI/ML"],
    ["neural network", "AI/ML"],
    ["neural networks", "AI/ML"],
    ["convolutional neural network", "AI/ML"],
    ["cnn", "AI/ML"],
    ["recurrent neural network", "AI/ML"],
    ["rnn", "AI/ML"],
    ["gan", "AI/ML"],
    ["generative ai", "AI/ML"],
    ["gpt", "AI/ML"],
    ["bert", "AI/ML"],
    ["stable diffusion", "AI/ML"],
    ["midjourney", "AI/ML"],
    ["mlops", "AI/ML"],
    ["mlflow", "AI/ML"],
    ["kubeflow", "AI/ML"],
    ["apache spark", "AI/ML"],
    ["spark", "AI/ML"],
    ["hadoop", "AI/ML"],
    ["airflow", "AI/ML"],
    ["apache airflow", "AI/ML"],
    ["dbt", "AI/ML"],
    ["data engineering", "AI/ML"],
    ["data pipeline", "AI/ML"],
    ["etl", "AI/ML"],
    ["feature engineering", "AI/ML"],
    ["model deployment", "AI/ML"],
    ["jupyter", "AI/ML"],
    ["jupyter notebook", "AI/ML"],
    ["matplotlib", "AI/ML"],
    ["seaborn", "AI/ML"],
    ["plotly", "AI/ML"],
    ["scipy", "AI/ML"],
    ["xgboost", "AI/ML"],
    ["lightgbm", "AI/ML"],
    ["catboost", "AI/ML"],
    ["rag", "AI/ML"],
    ["retrieval augmented generation", "AI/ML"],
    ["vector database", "AI/ML"],
    ["pinecone", "AI/ML"],
    ["weaviate", "AI/ML"],
    ["chromadb", "AI/ML"],

    // ─── Tools & Platforms (45+) ────────────────────────────
    ["git", "Tools"],
    ["github", "Tools"],
    ["gitlab", "Tools"],
    ["bitbucket", "Tools"],
    ["jira", "Tools"],
    ["confluence", "Tools"],
    ["figma", "Tools"],
    ["sketch", "Tools"],
    ["adobe xd", "Tools"],
    ["invision", "Tools"],
    ["postman", "Tools"],
    ["insomnia", "Tools"],
    ["swagger", "Tools"],
    ["openapi", "Tools"],
    ["webpack", "Tools"],
    ["vite", "Tools"],
    ["rollup", "Tools"],
    ["esbuild", "Tools"],
    ["parcel", "Tools"],
    ["turbopack", "Tools"],
    ["eslint", "Tools"],
    ["prettier", "Tools"],
    ["husky", "Tools"],
    ["lint-staged", "Tools"],
    ["npm", "Tools"],
    ["yarn", "Tools"],
    ["pnpm", "Tools"],
    ["maven", "Tools"],
    ["gradle", "Tools"],
    ["pip", "Tools"],
    ["cargo", "Tools"],
    ["homebrew", "Tools"],
    ["vs code", "Tools"],
    ["visual studio code", "Tools"],
    ["visual studio", "Tools"],
    ["intellij", "Tools"],
    ["intellij idea", "Tools"],
    ["webstorm", "Tools"],
    ["pycharm", "Tools"],
    ["xcode", "Tools"],
    ["android studio", "Tools"],
    ["eclipse", "Tools"],
    ["vim", "Tools"],
    ["neovim", "Tools"],
    ["emacs", "Tools"],
    ["sublime text", "Tools"],
    ["notion", "Tools"],
    ["slack", "Tools"],
    ["trello", "Tools"],
    ["asana", "Tools"],
    ["linear", "Tools"],
    ["monday.com", "Tools"],
    ["miro", "Tools"],
    ["lucidchart", "Tools"],

    // ─── Concepts & Methodologies (50+) ─────────────────────
    ["rest api", "Concepts"],
    ["restful", "Concepts"],
    ["rest", "Concepts"],
    ["graphql", "Concepts"],
    ["grpc", "Concepts"],
    ["websocket", "Concepts"],
    ["websockets", "Concepts"],
    ["microservices", "Concepts"],
    ["monolith", "Concepts"],
    ["serverless", "Concepts"],
    ["ci/cd", "Concepts"],
    ["continuous integration", "Concepts"],
    ["continuous delivery", "Concepts"],
    ["continuous deployment", "Concepts"],
    ["agile", "Concepts"],
    ["scrum", "Concepts"],
    ["kanban", "Concepts"],
    ["tdd", "Concepts"],
    ["test-driven development", "Concepts"],
    ["bdd", "Concepts"],
    ["behavior-driven development", "Concepts"],
    ["oop", "Concepts"],
    ["object-oriented programming", "Concepts"],
    ["functional programming", "Concepts"],
    ["design patterns", "Concepts"],
    ["solid principles", "Concepts"],
    ["clean architecture", "Concepts"],
    ["domain-driven design", "Concepts"],
    ["ddd", "Concepts"],
    ["event-driven architecture", "Concepts"],
    ["cqrs", "Concepts"],
    ["event sourcing", "Concepts"],
    ["system design", "Concepts"],
    ["distributed systems", "Concepts"],
    ["high availability", "Concepts"],
    ["scalability", "Concepts"],
    ["load balancing", "Concepts"],
    ["caching", "Concepts"],
    ["message queue", "Concepts"],
    ["message queues", "Concepts"],
    ["pub/sub", "Concepts"],
    ["api design", "Concepts"],
    ["authentication", "Concepts"],
    ["authorization", "Concepts"],
    ["oauth", "Concepts"],
    ["oauth2", "Concepts"],
    ["jwt", "Concepts"],
    ["saml", "Concepts"],
    ["sso", "Concepts"],
    ["single sign-on", "Concepts"],
    ["encryption", "Concepts"],
    ["ssl", "Concepts"],
    ["tls", "Concepts"],
    ["https", "Concepts"],
    ["security", "Concepts"],
    ["penetration testing", "Concepts"],
    ["owasp", "Concepts"],
    ["accessibility", "Concepts"],
    ["a11y", "Concepts"],
    ["responsive design", "Concepts"],
    ["mobile-first", "Concepts"],
    ["seo", "Concepts"],
    ["performance optimization", "Concepts"],
    ["code review", "Concepts"],
    ["pair programming", "Concepts"],
    ["mob programming", "Concepts"],
    ["version control", "Concepts"],
    ["trunk-based development", "Concepts"],
    ["gitflow", "Concepts"],
    ["monorepo", "Concepts"],
    ["data structures", "Concepts"],
    ["algorithms", "Concepts"],

    // ─── Soft Skills (35+) ──────────────────────────────────
    ["leadership", "Soft Skills"],
    ["communication", "Soft Skills"],
    ["problem-solving", "Soft Skills"],
    ["problem solving", "Soft Skills"],
    ["teamwork", "Soft Skills"],
    ["collaboration", "Soft Skills"],
    ["mentoring", "Soft Skills"],
    ["mentorship", "Soft Skills"],
    ["project management", "Soft Skills"],
    ["time management", "Soft Skills"],
    ["critical thinking", "Soft Skills"],
    ["analytical thinking", "Soft Skills"],
    ["creative thinking", "Soft Skills"],
    ["decision making", "Soft Skills"],
    ["conflict resolution", "Soft Skills"],
    ["negotiation", "Soft Skills"],
    ["presentation", "Soft Skills"],
    ["public speaking", "Soft Skills"],
    ["stakeholder management", "Soft Skills"],
    ["cross-functional", "Soft Skills"],
    ["cross-functional collaboration", "Soft Skills"],
    ["adaptability", "Soft Skills"],
    ["attention to detail", "Soft Skills"],
    ["self-motivated", "Soft Skills"],
    ["initiative", "Soft Skills"],
    ["strategic thinking", "Soft Skills"],
    ["strategic planning", "Soft Skills"],
    ["emotional intelligence", "Soft Skills"],
    ["empathy", "Soft Skills"],
    ["customer focus", "Soft Skills"],
    ["customer-centric", "Soft Skills"],
    ["results-driven", "Soft Skills"],
    ["proactive", "Soft Skills"],
    ["resilience", "Soft Skills"],
    ["coaching", "Soft Skills"],
    ["delegation", "Soft Skills"],
    ["interpersonal skills", "Soft Skills"],
    ["remote work", "Soft Skills"],
    ["work ethic", "Soft Skills"],
];

/**
 * Tech keyword database: maps lowercase skill name → category.
 * Contains 500+ entries covering programming languages, frameworks,
 * databases, cloud, DevOps, AI/ML, tools, concepts, and soft skills.
 */
export const TECH_KEYWORD_DATABASE: Map<string, string> = new Map(entries);

// ── Action Verbs (150+) ────────────────────────────────────

/**
 * Strong resume action verbs categorized by theme.
 * Used by the bullet quality scorer to detect strong opener verbs.
 */
export const ACTION_VERBS: string[] = [
    // Leadership
    "led",
    "directed",
    "managed",
    "supervised",
    "coordinated",
    "mentored",
    "oversaw",
    "spearheaded",
    "championed",
    "guided",
    "headed",
    "governed",
    "administered",
    "orchestrated",
    "delegated",
    "mobilized",

    // Achievement
    "achieved",
    "exceeded",
    "improved",
    "increased",
    "reduced",
    "optimized",
    "boosted",
    "accelerated",
    "surpassed",
    "delivered",
    "completed",
    "accomplished",
    "attained",
    "maximized",
    "minimized",
    "streamlined",
    "enhanced",
    "elevated",
    "outperformed",

    // Technical
    "developed",
    "implemented",
    "designed",
    "architected",
    "engineered",
    "built",
    "coded",
    "programmed",
    "deployed",
    "configured",
    "integrated",
    "migrated",
    "automated",
    "refactored",
    "debugged",
    "resolved",
    "patched",
    "maintained",
    "upgraded",
    "modernized",
    "scaled",
    "containerized",
    "provisioned",
    "instrumented",
    "benchmarked",
    "compiled",
    "optimized",
    "parallelized",

    // Analysis
    "analyzed",
    "evaluated",
    "assessed",
    "researched",
    "investigated",
    "identified",
    "diagnosed",
    "discovered",
    "measured",
    "monitored",
    "tracked",
    "audited",
    "reviewed",
    "inspected",
    "tested",
    "validated",
    "verified",
    "profiled",
    "surveyed",
    "examined",

    // Communication
    "presented",
    "collaborated",
    "negotiated",
    "facilitated",
    "communicated",
    "documented",
    "reported",
    "advocated",
    "influenced",
    "persuaded",
    "advised",
    "consulted",
    "recommended",
    "proposed",
    "briefed",
    "translated",
    "articulated",
    "mediated",
    "liaised",

    // Creative / Initiative
    "created",
    "innovated",
    "launched",
    "pioneered",
    "initiated",
    "invented",
    "introduced",
    "established",
    "founded",
    "conceptualized",
    "prototyped",
    "formulated",
    "devised",
    "crafted",
    "envisioned",

    // Process
    "standardized",
    "systematized",
    "consolidated",
    "centralized",
    "restructured",
    "reorganized",
    "revamped",
    "transformed",
    "overhauled",
    "reengineered",
    "simplified",
    "unified",
    "harmonized",

    // Training / Teaching
    "trained",
    "taught",
    "educated",
    "coached",
    "onboarded",
    "tutored",
    "instructed",
    "empowered",
    "cultivated",
    "developed",

    // Financial / Business
    "budgeted",
    "forecasted",
    "generated",
    "secured",
    "acquired",
    "procured",
    "allocated",
    "saved",
    "earned",
    "capitalized",
    "leveraged",
    "monetized",
];

// ── Weak Verbs (to avoid) ──────────────────────────────────

/**
 * Weak resume verbs that should be replaced with stronger action verbs.
 * These are commonly flagged by ATS systems and career coaches.
 */
export const WEAK_VERBS: string[] = [
    "helped",
    "assisted",
    "worked on",
    "responsible for",
    "participated in",
    "involved in",
    "contributed to",
    "handled",
    "utilized",
    "tasked with",
    "dealt with",
    "was part of",
    "supported",
    "aided",
    "tried",
    "attempted",
    "did",
    "made",
    "got",
    "went",
    "used",
    "had",
];
