@direction TB
@spacing 60

(User Browser) -> [Next.js App - Vercel Free]
[Next.js App - Vercel Free] -> [API Routes Layer]
[API Routes Layer] -> [Auth Module - NextAuth.js]
[API Routes Layer] -> [Resume Module]
[API Routes Layer] -> [AI Module]
[API Routes Layer] -> [Export Module]
[API Routes Layer] -> [Analytics Module]
[Resume Module] -> [[Neon PostgreSQL Free]]
[Resume Module] -> [[Upstash Redis Cache]]
[Resume Module] -> [[Cloudflare R2 Storage]]
[Resume Module] -> [QStash Background Jobs]
[AI Module] -> [[Upstash Redis Cache]]
[AI Module] -> [LLM Provider Interface]
[LLM Provider Interface] -> [Gemini API Free Tier]
[LLM Provider Interface] -> [Groq API Free Tier]
[QStash Background Jobs] -> [Resume Parser Worker]
[QStash Background Jobs] -> [PDF Export Worker]
[QStash Background Jobs] -> [AI Batch Worker]
[Resume Parser Worker] -> [[Neon PostgreSQL Free]]
[Resume Parser Worker] -> [[Cloudflare R2 Storage]]
[Analytics Module] -> [Umami Self-Hosted]
[Auth Module - NextAuth.js] -> [[Neon PostgreSQL Free]]
[Export Module] -> [[Cloudflare R2 Storage]]
[API Routes Layer] -> [Ad Component Slots]
[Ad Component Slots] -> [Google AdSense]
